# name of the package to generate, e.g. pydra.tasks.mriqc
name: pydra.tasks.afni
# name of the nipype package to generate from (e.g. mriqc)
nipype_name: nipype.interfaces.afni
# The name of the global struct/dict that contains workflow inputs that are to be converted to inputs of the function along with the type of the struct, either "dict" or "class"
config_params: null
# Mappings between nipype packages and their pydra equivalents. Regular expressions are supported
import_translations: null
find_replace:
  - [
      "list\\(self\\.inputs\\.traits\\(\\*\\*metadata\\)\\.keys\\(\\)\\)",
      "list(inputs)",
    ]
  - ["\\s+metadata = dict\\(name_source=lambda t: t is not None\\)", ""]
  - ["\\s+config = NipypeConfig\\(\\)", ""]
  - ["\\slogging = Logging\\(config\\)", ""]
import_find_replace:
  - ["\\s+config,(\\s+)fname_presuffix,", "\\1fname_presuffix,"]
